site_name: Klantinteractie Servicesysteem
site_url: https://readthedocs.org/projects/klantinteractie-servicesysteem/

nav:
  - Home: index.md
  - Installatie: INSTALLATION.md
  - Configuratie: CONFIGURATIE.md
  - Definition of Done: DEFINITIONOFDONE.md
  - Security: SECURITY.md
  
theme: readthedocs
